# Generated by Django 5.0.6 on 2024-06-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="title",
        ),
    ]
