# Generated by Django 5.0.6 on 2024-06-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_response_user_id_form_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="answer_choice",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
